### ISSUE TITLE
Decide on formatting rules

### ISSUE THREAD

**Issue by CoffeeCoder1** [samsface/godot-pure-data#13]
We should decide on a code style to keep things consistent between contributors (helps with readability of code and should help reduce merge conflicts if done right). For C++, it may be a good idea to just use [Godot's C++ code style](https://github.com/godotengine/godot/blob/master/.clang-format) to keep things consistent with other Godot C++ projects, and for other languages we can probably just use a generic editorconfig file.

**Comment by samsface** [comment]
Yeah I like Godot's coding guidelines.

**Comment by CoffeeCoder1** [comment]
I have added Godot's `.cmake-format` and `.editorconfig` files to the repo and created a PR which formats all of the C++ files (#16).
