### ISSUE TITLE
Improve the demo project

### ISSUE THREAD

**Issue by CoffeeCoder1** [samsface/godot-pure-data#8]
The demo project isn't really functional right now and the addon in the demo doesn't get updated when new builds are made, so it should probably be worked on a bit. If we end up using GitHub releases to distribute releases (#4), the CI build process should also be adapted a bit so the demo gets included with those releases (a pretty good example of how to do this is [Terrain3D](https://github.com/TokisanGames/Terrain3D), which also uses releases to distribute builds).

**Comment by CoffeeCoder1** [comment]
I have some initial work done on packaging the demo on [this branch](https://github.com/CoffeeCoder1/godot-pure-data/tree/package-demo).

**Comment by samsface** [comment]
@CoffeeCoder1 yeah the demo broke after an API change I made :disappointed:  I've been meaning to write a better one but can't give an ETA atm.
